const productData = [
  {
    id: 1,
    Title: "Product 1",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPhSZfU6WZxvRm6MqjW83s_quEwwFwMyKBdA&usqp=CAU",
    price: 200,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 2,
    Title: "Product 2",
    img: "https://media.istockphoto.com/id/1350560575/photo/pair-of-blue-running-sneakers-on-white-background-isolated.webp?b=1&s=170667a&w=0&k=20&c=liUSgX6SafJ7HWvefFqR9-pnf3KuH6v1lwQ6iEpePWc=",
    price: 1200,
    Des: "this is my first product",
    cat: "shoes",
  },
  {
    id: 3,
    Title: "Product 3",
    img: "https://media.istockphoto.com/id/471435551/photo/laptop-bag-with-blank-sticker.jpg?s=1024x1024&w=is&k=20&c=2_HTa5R5QapAh6WqvbUZOUcrP84iASYS2vnLMb5YpyQ=",
    price: 1700,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 4,
    Title: "Product 4",
    img: "https://www.shutterstock.com/image-photo/blank-template-black-down-jacket-260nw-1239023359.jpg",
    price: 3000,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 5,
    Title: "Product 5",
    img: "https://th.bing.com/th/id/R.40a864675b0908dd4344a5c1a4d7cf3c?rik=NXagyI%2bbjeb0kQ&pid=ImgRaw&r=0",
    price: 500,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 6,
    Title: "Product 6",
    img: "https://th.bing.com/th/id/OIP.bkNoqJYmA_iAKzhsv8sifAAAAA?pid=ImgDet&rs=1",
    price: 200,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 7,
    Title: "Product 7",
    img: "https://th.bing.com/th/id/R.aba213deff26acc011a0a7853b2dd64b?rik=1lRVQs4uVwFWWg&pid=ImgRaw&r=0",
    price: 2400,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 8,
    Title: "Product 8",
    img: "https://th.bing.com/th/id/OIP.TOdDYGmOVz5HvGvd0KAgvgHaHa?pid=ImgDet&rs=1",
    price: 2000,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 9,
    Title: "Product 9",
    img: "https://th.bing.com/th/id/R.9552aacc226ff437036b1f36de70d3b9?rik=eCmfToPRh0KQ7A&pid=ImgRaw&r=0",
    price: 4000,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 10,
    Title: "Product 10",
    img: "https://th.bing.com/th/id/OIP.H3L_2Z3pQo-i9S24l2U8TwHaE8?pid=ImgDet&rs=1",
    price: 65000,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 11,
    Title: "Product 11",
    img: "https://th.bing.com/th/id/OIP.rekPVo1Ntf3jYHoTClxjFgHaHP?pid=ImgDet&rs=1",
    price: 20000,
    Des: "this is my first product",
    cat: "mug",
  },
  {
    id: 12,
    Title: "Product 12",
    img: "https://th.bing.com/th/id/R.424982672d2a259a7341cfaa80c334e0?rik=bRZf5P13FMvZPw&pid=ImgRaw&r=0",
    price: 10000,
    Des: "this is my first product",
    cat: "mug",
  },
];
export default productData;
